package ead_assignment;
// Generated Oct 14, 2017 3:53:01 PM by Hibernate Tools 4.3.1



/**
 * EmployeeTasksId generated by hbm2java
 */
public class EmployeeTasksId  implements java.io.Serializable {


     private Integer employee;
     private Integer task;

    public EmployeeTasksId() {
    }

    public EmployeeTasksId(Integer employee, Integer task) {
       this.employee = employee;
       this.task = task;
    }
   
    public Integer getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Integer employee) {
        this.employee = employee;
    }
    public Integer getTask() {
        return this.task;
    }
    
    public void setTask(Integer task) {
        this.task = task;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmployeeTasksId) ) return false;
		 EmployeeTasksId castOther = ( EmployeeTasksId ) other; 
         
		 return ( (this.getEmployee()==castOther.getEmployee()) || ( this.getEmployee()!=null && castOther.getEmployee()!=null && this.getEmployee().equals(castOther.getEmployee()) ) )
 && ( (this.getTask()==castOther.getTask()) || ( this.getTask()!=null && castOther.getTask()!=null && this.getTask().equals(castOther.getTask()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmployee() == null ? 0 : this.getEmployee().hashCode() );
         result = 37 * result + ( getTask() == null ? 0 : this.getTask().hashCode() );
         return result;
   }   


}


