package ead_assignment;
// Generated Oct 14, 2017 3:53:01 PM by Hibernate Tools 4.3.1



/**
 * EmployeeTasks generated by hbm2java
 */
public class EmployeeTasks  implements java.io.Serializable {


     private EmployeeTasksId id;

    public EmployeeTasks() {
    }

    public EmployeeTasks(EmployeeTasksId id) {
       this.id = id;
    }
   
    public EmployeeTasksId getId() {
        return this.id;
    }
    
    public void setId(EmployeeTasksId id) {
        this.id = id;
    }




}


