package Models;
// Generated Oct 14, 2017 3:53:01 PM by Hibernate Tools 4.3.1



/**
 * Task generated by hbm2java
 */
public class Task  implements java.io.Serializable {


     private int taskid;
     private String description;
     private Integer employee;

    public Task() {
    }

	
    public Task(int taskid) {
        this.taskid = taskid;
    }
    public Task(int taskid, String description, Integer employee) {
       this.taskid = taskid;
       this.description = description;
       this.employee = employee;
    }
   
    public int getTaskid() {
        return this.taskid;
    }
    
    public void setTaskid(int taskid) {
        this.taskid = taskid;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Integer employee) {
        this.employee = employee;
    }




}


